context:
  version: 2014.12.24

package:
  name: coco
  version: ${{ version }}

source:
  url: https://github.com/boogie-org/coco/archive/${{ version }}.tar.gz
  sha256: a92918222963befc8e09c447bd59881ba1fadb1aa4c5ec577ff12f82e7c23560

build:
  number: 1
  noarch: generic

requirements:
  host:
    - dotnet
    - sed
  run:
    - dotnet

tests:
  - script:
      - coco 2>&1 | grep -q 'Usage: "Coco Grammar.ATG {Option}'"

about:
  license: GPL-2.0-or-later
  license_file: license.txt
  summary: The compiler generator Coco/R
  homepage: https://github.com/boogie-lang/coco
  repository: https://github.com/boogie-lang/coco

extra:
  recipe-maintainers:
    - danielnachun
